name: instant_gram
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  appwrite: ^9.0.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  fpdart: ^0.6.0
  go_router: ^9.0.3
  image_picker: ^1.0.0
  intl: ^0.18.1
  package_info_plus: ^4.0.2
  path_provider: ^2.0.15
  uuid: ^3.0.7
  video_player: ^2.7.0
  video_thumbnail: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
